import React, { useEffect, useState } from 'react';
import { Columns2, Loader2, X } from 'lucide-react';
import { getDocument } from '../lib/api';

export default function DocumentComparison({ documents, onClose }) {
  const [details, setDetails] = useState([]); const [error, setError] = useState('');
  useEffect(() => { let live = true; Promise.all(documents.map((doc) => getDocument(doc.id))).then((items) => live && setDetails(items)).catch((err) => live && setError(err.message || 'Unable to load documents for comparison')); return () => { live = false; }; }, [documents]);
  return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/45 p-4" role="presentation" onMouseDown={onClose}><section className="flex max-h-[90vh] w-full max-w-6xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="compare-title" onMouseDown={(event) => event.stopPropagation()}><header className="flex items-center justify-between border-b border-slate-200 p-5"><div className="flex items-center gap-2"><Columns2 className="h-5 w-5 text-teal-600" /><h2 id="compare-title" className="text-lg font-bold text-slate-900">Document comparison</h2></div><button type="button" onClick={onClose} className="text-slate-400 hover:text-slate-700" aria-label="Close document comparison"><X className="h-5 w-5" /></button></header>{error ? <p className="p-8 text-sm text-red-600">{error}</p> : details.length !== 2 ? <div className="flex items-center justify-center gap-2 p-16 text-sm text-slate-500"><Loader2 className="h-5 w-5 animate-spin text-teal-600" />Loading document content…</div> : <div className="grid flex-1 grid-cols-1 divide-y divide-slate-200 overflow-y-auto md:grid-cols-2 md:divide-x md:divide-y-0">{details.map((detail, index) => <article key={documents[index].id} className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-teal-600">Document {index + 1}</p><h3 className="mt-1 text-lg font-bold text-slate-900">{documents[index].filename}</h3><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-slate-400">Type</dt><dd className="font-semibold text-slate-700">{documents[index].file_type?.toUpperCase() || '—'}</dd></div><div><dt className="text-slate-400">Pages</dt><dd className="font-semibold text-slate-700">{documents[index].pages_count || '—'}</dd></div><div><dt className="text-slate-400">Entities</dt><dd className="font-semibold text-slate-700">{detail.entities?.length || 0}</dd></div><div><dt className="text-slate-400">Relationships</dt><dd className="font-semibold text-slate-700">{detail.relationships?.length || 0}</dd></div></dl><div className="mt-5 border-t border-slate-100 pt-4"><p className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-400">Extracted preview</p><p className="max-h-72 overflow-y-auto whitespace-pre-wrap text-sm leading-relaxed text-slate-600">{detail.content_preview || 'No preview is available for this document.'}</p></div></article>)}</div>}</section></div>;
}
